In [84]:
import numpy as np
#Отсортировать значения массива по частоте встречания.

np.random.seed(18182)
a = np.random.randint(5, size=10)
print(a)
uniqs, freq = np.unique(a, return_counts=True)
print(uniqs,freq)
indices = np.argsort(freq)
uniqs[indices]


[2 3 3 4 1 1 1 3 4 2]
[1 2 3 4] [3 2 3 2]


array([2, 4, 1, 3])

In [78]:
#Дана картинка высоты h, ширины w, тип данных np.uint8 (от 0 до 255). Найти количество уникальных цветов.
np.random.seed(18182)
h = 1000
w = 1000
a = np.random.randint(255, size=[3,h,w])


a = np.column_stack([a[0].reshape([1, -1]).transpose(), a[1].reshape([1, -1]).transpose(), a[2].reshape([1, -1]).transpose()])

uniqs, freq = np.unique(a, axis=0, return_counts=True)

len(uniqs)

970101

In [90]:
#Написать функцию, вычислающую плавающее среднее вектора

def moving_average(arr):
  return np.multiply(arr, 1 / len(arr))


a = np.array([
    1,2,3,4
])

moving_average(a)

array([0.25, 0.5 , 0.75, 1.  ])

In [164]:
#Дана матрица (n, 3). Вывести те тройки чисел, которые являются длинами сторон треугольника.

def is_triangle(arr):
  return (arr[0] + arr[1] > arr[2]) and (arr[1] + arr[2] > arr[0]) and (arr[0] + arr[2] > arr[1])

np.random.seed(18182)
n = 10
a = np.random.randint(255, size=[n,3])
is_tr = np.array(list(map(is_triangle, a)))
print(a)
print(a[np.where(is_tr==True)])

[[122 115 107]
 [172   1 145]
 [221 129  21]
 [ 19 173  15]
 [ 68  10   7]
 [144  96 249]
 [229 103  80]
 [245  20  44]
 [249  68 142]
 [ 95  23 249]]
[[122 115 107]]
